test1-20251113-145816:
  id: test1-20251113-145816
  name: test1
  description: ''
  tags: []
  created_at: '2025-11-13T14:58:16.923790'
  status: created
  metadata:
    services:
      gpt-oss-120b-openrouter-fireworks:
        stage: analysis
        overrides:
        - client_max_requests=5
        reuse_from_run: null
        timestamp: '2025-11-13T16:05:55.528108'
        model: gpt-oss-120b
        provider: openrouter-fireworks
    default_overrides:
    - client_max_requests=5
  updated_at: '2025-11-13T16:05:55.529175'
